name: Build and Deploy

on:
  push:
    branches:
      - main # Or whichever branch you want to target

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-react-app .

    # If you were to push to a registry, this would be where you do it
    # - name: Push Docker image
    #   run: |
    #     docker login ...
    #     docker push ...

    - name: Run Docker container
      run: |
        # Stopping any previous instance of the container (optional)
        docker stop auth-server-front || true
        docker rm auth-server-front || true

        # Running the Docker image
        docker run -d --name auth-server-front -p 4201:80 my-react-app